# fly.toml app configuration file generated for nbs-api on 2024-09-02T20:12:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nbs-api'
primary_region = 'ams'

[build]

[deploy]
  release_command = 'alembic upgrade head'
  strategy = 'bluegreen'

[env]
  PORT = '8080'
  PRIMARY_REGION = 'ams'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 20
    soft_limit = 10

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
