# fly.toml app configuration file generated for nbs-api on 2024-09-02T20:12:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nbs-api'
primary_region = 'ams'

[build]

[deploy]
  release_command = 'uv run alembic upgrade head'
  strategy = 'bluegreen'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
