"""add_specialized_impacts

Revision ID: 1575eedda88f
Revises: a85c82055f0b
Create Date: 2025-06-15 12:58:02.481382+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1575eedda88f"
down_revision = "a85c82055f0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specialized_impact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("impact_id", sa.Integer(), nullable=False),
        sa.Column(
            "climate_data",
            sa.JSON(),
            nullable=True,
            comment="Climate-related impact metrics (temp_reduction, cool_spot, etc.)",
        ),
        sa.Column(
            "water_quality_data",
            sa.JSON(),
            nullable=True,
            comment="Water quality impact metrics (capture_unit, filtering_unit, etc.)",
        ),
        sa.Column(
            "cost_data",
            sa.JSON(),
            nullable=True,
            comment="Cost-related metrics (construction_cost, maintenance_cost, etc.)",
        ),
        sa.ForeignKeyConstraint(["impact_id"], ["impact.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("impact_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("specialized_impact")
    # ### end Alembic commands ###
