"""one-to-many solution-impacts

Revision ID: 28b692db0508
Revises: 53401ffc047b
Create Date: 2024-11-26 14:46:34.012648+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b692db0508'
down_revision = '53401ffc047b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impact', sa.Column('solution_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'impact', 'naturebasedsolution', ['solution_id'], ['id'])
    op.alter_column('impact_unit', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('naturebasedsolution_impact_id_key', 'naturebasedsolution', type_='unique')
    op.drop_constraint('naturebasedsolution_impact_id_fkey', 'naturebasedsolution', type_='foreignkey')
    op.drop_column('naturebasedsolution', 'impact_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('naturebasedsolution', sa.Column('impact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('naturebasedsolution_impact_id_fkey', 'naturebasedsolution', 'impact', ['impact_id'], ['id'])
    op.create_unique_constraint('naturebasedsolution_impact_id_key', 'naturebasedsolution', ['impact_id'])
    op.alter_column('impact_unit', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'impact', type_='foreignkey')
    op.drop_column('impact', 'solution_id')
    # ### end Alembic commands ###
