"""add_physical_properties

Revision ID: 59748ffffc95
Revises: 1575eedda88f
Create Date: 2025-06-16 10:52:19.529621+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "59748ffffc95"
down_revision = "1575eedda88f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "naturebasedsolution",
        sa.Column(
            "physical_properties",
            sa.JSON(),
            nullable=True,
            comment="Physical dimensions and properties",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("naturebasedsolution", "physical_properties")
    # ### end Alembic commands ###
