"""empty message

Revision ID: 858ab3cfa441
Revises: 196c07f66489
Create Date: 2024-10-15 13:15:43.004523+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858ab3cfa441'
down_revision = '196c07f66489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=False))
    op.drop_index('ix_user_slug', table_name='user')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_user_slug', 'user', ['slug'], unique=True)
    op.drop_column('user', 'disabled')
    # ### end Alembic commands ###
