"""add_styling_to_nbs

Revision ID: a85c82055f0b
Revises: 28b692db0508
Create Date: 2025-06-05 10:48:15.700142+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a85c82055f0b"
down_revision = "28b692db0508"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("naturebasedsolution", sa.Column("styling", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("naturebasedsolution", "styling")
    # ### end Alembic commands ###
