"""empty message

Revision ID: bc341db95b36
Revises: 5df56a7878af
Create Date: 2024-10-24 14:31:59.032235+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc341db95b36'
down_revision = '5df56a7878af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_intensity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_intensity_intensity'), 'impact_intensity', ['intensity'], unique=True)
    op.create_table('impact_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_unit_unit'), 'impact_unit', ['unit'], unique=True)
    op.create_table('impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('intensity_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intensity_id'], ['impact_intensity.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['impact_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_description'), 'impact', ['description'], unique=False)
    op.create_index(op.f('ix_impact_magnitude'), 'impact', ['magnitude'], unique=False)
    op.add_column('naturebasedsolution', sa.Column('impact_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'naturebasedsolution', ['impact_id'])
    op.create_foreign_key(None, 'naturebasedsolution', 'impact', ['impact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'naturebasedsolution', type_='foreignkey')
    op.drop_constraint(None, 'naturebasedsolution', type_='unique')
    op.drop_column('naturebasedsolution', 'impact_id')
    op.drop_index(op.f('ix_impact_magnitude'), table_name='impact')
    op.drop_index(op.f('ix_impact_description'), table_name='impact')
    op.drop_table('impact')
    op.drop_index(op.f('ix_impact_unit_unit'), table_name='impact_unit')
    op.drop_table('impact_unit')
    op.drop_index(op.f('ix_impact_intensity_intensity'), table_name='impact_intensity')
    op.drop_table('impact_intensity')
    # ### end Alembic commands ###
