"""add_project_model

Revision ID: ea7ce84afd65
Revises: 59748ffffc95
Create Date: 2025-06-16 10:53:38.185271+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ea7ce84afd65"
down_revision = "59748ffffc95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "settings",
            sa.JSON(),
            nullable=True,
            comment="Project-level settings (scenario, capacity, etc.)",
        ),
        sa.Column(
            "map_settings",
            sa.JSON(),
            nullable=True,
            comment="Map display settings (center, zoom, base layer)",
        ),
        sa.Column(
            "targets",
            sa.JSON(),
            nullable=True,
            comment="Project targets for different impact categories",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_title"), "project", ["title"], unique=False)
    op.create_table(
        "project_nbs_assoc",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("nbs_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["nbs_id"], ["naturebasedsolution.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "nbs_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_nbs_assoc")
    op.drop_index(op.f("ix_project_title"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
