openapi: 3.0.0
info:
  title: Nature-Based Solutions API
  version: 1.0.0
  description: API for retrieving nature-based solutions for excess heat and flooding within a specified bounding box or GeoJSON polygon.
  
servers:
  - url: http://localhost:8000

paths:
  /solutions:
    get:
      summary: Retrieve nature-based solutions
      description: Retrieve nature-based solutions for either excess heat or flooding within a given bounding box or GeoJSON polygon.
      parameters:
        - in: query
          name: category
          required: true
          schema:
            type: string
            enum:
              - heat
              - flooding
          description: The category of nature-based solutions to retrieve.
        - in: query
          name: bbox
          required: false
          schema:
            type: array
            items:
              type: number
            minItems: 4
            maxItems: 4
            example: [-74.1, 40.7, -73.9, 40.8]
          description: Bounding box specified as [west, south, east, north].
        - in: query
          name: geojson
          required: false
          schema:
            type: string
            format: geojson
          description: GeoJSON polygon specifying the area of interest.

      responses:
        '200':
          description: A list of nature-based solutions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NatureBasedSolution'
        '400':
          description: Invalid parameters

  /solutions/trees:
    get:
      summary: Retrieve information about trees as a solution for excess heat
      description: Get detailed information on how trees can mitigate excess heat.
      responses:
        '200':
          description: Detailed information about trees
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NatureBasedSolution'

  /solutions/bioswales:
    get:
      summary: Retrieve information about bioswales as a solution for flooding
      description: Get detailed information on how bioswales can mitigate flooding.
      responses:
        '200':
          description: Detailed information about bioswales
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NatureBasedSolution'

components:
  schemas:
    NatureBasedSolution:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        category:
          type: string
        effectiveness:
          type: string
        location:
          type: string
        geometry:
          type: object
          additionalProperties: true
      required:
        - name
        - description
        - category
        - effectiveness
        - location
